Update vhost_sock_dir ML2 setting
The `vhost_sock_dir` ML2 ovn setting specifies the location
where Libvirt will place vhost-user unix sockets consumed
by ovs.

Right now, attempting to use vhost-user (dpdk) ports fails
since `/run/libvirt-vhost-user` doesn't exist:

```
libvirt.libvirtError: internal error: process exited while connecting
to monitor: 2025-08-08T08:09:05.144128Z qemu-system-x86_64:
-chardev socket,id=charnet0,path=/run/libvirt-vhost-user/vhu6a1804f8-e7,server=on:
Failed to bind socket to /run/libvirt-vhost-user/vhu6a1804f8-e7: No such file or directory
```

We'll configure it to use the Libvirt socket dir instead:
`/var/snap/openstack-hypervisor/common/run/libvirt`
https://github.com/canonical/snap-openstack-hypervisor/blob/c315284fc5d3fd34dbe3fe0b4ef154a94dbe1a0f/templates/libvirtd.conf.j2#L115

Change-Id: Id588b03de7b805f9ddfd0753d2b262c4df1cbfc4
Signed-off-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>