Update dependencies
"cryptography" and "pydantic" depend on "maturin",
which fails to install from source.

"cryptography" was already added to the "charm-binary-python-packages"
list, allowing prebuilt packages to be used. However, our uv.lock
files contain a slightly older version so charmcraft attempts to
install it from source and fails:

  ModuleNotFoundError: No module named 'puccinialin'

This patch will fix the build failures by:

* updating the uv.lock files (tox -e lock)
* adding pydantic to the list of binary packages

Cryptography 44.0.2 currently fails to install:
https://pastebin.canonical.com/p/Z4ZZhqWwtV/plain/

Change-Id: Ibfe555df7f72b867ad92c3bb00bb6fa576d7b0fc
(cherry picked from commit d8094c2a11af24f02240bd50590798295d721b6a)