Simplify test add_certificate_relation
Sometimes the CI for py3 fails with error
AttributeError: 'str' object has no attribute '_private_key'

Simplify the add_certificate_relation in
test_utils.py to use harness.add_relation
with necessary app_data and unit_data

Change-Id: I045f04e665516769214f88487e73b27d24b3d63c
Signed-off-by: Hemanth Nakkina <hemanth.nakkina@canonical.com>
(cherry picked from commit 036b99a33354c6b811f97fc38e2fb047460bb85a)